"""Add conversation model, refactor message model to account for conversations

Revision ID: 8056ed843831
Revises: cdc93ac0c9d4
Create Date: 2025-07-22 18:21:06.718535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8056ed843831'
down_revision = 'cdc93ac0c9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('received_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', sa.UUID(), nullable=False))
        batch_op.alter_column('read_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('messages_animal_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_shelter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])
        batch_op.drop_column('sent_time')
        batch_op.drop_column('received_time')
        batch_op.drop_column('animal_id')
        batch_op.drop_column('conversation')
        batch_op.drop_column('private')
        batch_op.drop_column('shelter_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('shelter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('shelter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('conversation', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('animal_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('received_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sent_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_shelter_id_fkey'), 'shelters', ['shelter_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_animal_id_fkey'), 'animals', ['animal_id'], ['id'])
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('read_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('content')
        batch_op.drop_column('received_at')
        batch_op.drop_column('created_at')

    op.drop_table('conversations')
    # ### end Alembic commands ###
