"""add verification table

Revision ID: 87598b7cd55a
Revises: db38d7615300
Create Date: 2025-08-18 18:18:16.677853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87598b7cd55a'
down_revision = 'db38d7615300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('verifications')
    # ### end Alembic commands ###
