"""add messages table

Revision ID: cdc93ac0c9d4
Revises: 1df2abed1930
Create Date: 2025-07-18 15:33:38.338135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc93ac0c9d4'
down_revision = '1df2abed1930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sent_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conversation', sa.UUID(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
