"""add verified column to user model

Revision ID: db38d7615300
Revises: 84e95f6b0e91
Create Date: 2025-08-12 15:48:49.775557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db38d7615300'
down_revision = '84e95f6b0e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        
    op.execute('UPDATE users SET verified = true')
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(sa.Column('verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
